platform :ios, '11.0'

use_frameworks!

target 'SnackView_Example' do
  pod 'SnackView', :path => '../'

  target 'SnackView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
